secretGenerator:
  - name: mysql-pass
    literals:
      - password=password

resources:
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - wordpress-pvc.yaml
  - wordpress-deployment.yaml
  - wordpress-service.yaml
  - wordpress-ingress.yaml
